[package]
name = "sensorforge-bosch-imu"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"

[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", features = ["eh1"] }

[features]
bmi160 = []
bmi323 = []
